
server:
  port: 8080 #서버가 사용할 포트 번호 설정
  servlet:
    encoding:
      charset: utf-8 #서블릿의 응답과 요청 인코딩을 UTF-8로 설정
      force: true # 요청과 응답에 대해 이 인코딩을 !강제!로 사용하도록 설정합니다.

spring:
  mustache:
    servlet:
      expose-session-attributes: true  # Mustache 템플릿에서 세션 속성에 접근할 수 있도록 허용
      expose-request-attributes: true  # Mustache 템플릿에서 요청 속성에 접근할 수 있도록 허용
    prefix: classpath:/templates/  # Mustache 템플릿 파일 경로 설정 (resources/templates)
    suffix: .mustache  # Mustache 템플릿 파일 확장자 설정

  datasource:
    url: jdbc:h2:mem:bankdb;MODE=MySQL # 데이터베이스 연결을 위한 URL 설정 (H2를 MySQL 모드로 사용)
    driver-class-name: org.h2.Driver # 드라이버 클래스 설정
    username: sa # 데이터베이스 사용자 ID
    password: '' # 데이터베이스 비밀번호 (빈 문자열)

  sql:
    init:
      schema-locations:
      - classpath:db/table.sql
      data-locations:
      - classpath:db/data.sql
    
  h2:
    console:
      enabled: true #H2 데이터 베이스 콘솔을 활성화합니다.
      
  output:
    ansi:
      enabled: always # 콘솔 출력에 ANSI 코드를 사용할 수 있도록 설정

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
# Mybatis 설정
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml # MyBatis 매퍼 파일 위치를 설정합니다. **은 모든 디렉토리를 의미하며, *.xml은 모든 xml 파일을 의미합니다.
  configuration:
    map-underscore-to-camel-case: true # 데이터베이스의 언더스코어 네이밍(column_name)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # SQL 로깅 구현체를 설정합니다.


logging:
  level:
    org.apache.ibatis: DEBUG # MyBatis 로깅 레벨을 DEBUG로 설정하여 실행되는 SQL 쿼리와 내부 로깅 정보를 콘솔에 출력한다.